export const SET_ORDER = "SET_ORDER";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const UPDATE_CONSTRUCTOR_INGREDIENT = "UPDATE_CONSTRUCTOR_INGREDIENT";
export const SET_CONSTRUCTOR_INGREDIENTS = "SET_CONSTRUCTOR_INGREDIENTS";
export const SET_BUN = "SET_BUN";
export const SET_TOTAL_SUM = "SET_TOTAL_SUM";