export const WS_ORDER_ALL_CONNECTION_START =
  "WS_ORDER_ALL_CONNECTION_START" as const;
export const WS_ORDER_ALL_SEND_MESSAGE = "WS_ORDER_ALL_SEND_MESSAGE" as const;
export const WS_ORDER_ALL_CLOSE = "WS_ORDER_ALL_CLOSE" as const;

export const WS_ORDER_CONNECTION_START = "WS_ORDER_CONNECTION_START" as const;
export const WS_ORDER_SEND_MESSAGE = "WS_ORDER_SEND_MESSAGE" as const;
export const WS_ORDER_CLOSE = "WS_ORDER_CLOSE" as const;
