export const WS_ORDER_ALL_CONNECTION_START = "WS_ORDER_ALL_CONNECTION_START";
export const WS_ORDER_ALL_SEND_MESSAGE = "WS_ORDER_ALL_SEND_MESSAGE";
export const WS_ORDER_ALL_CLOSE = "WS_ORDER_ALL_CLOSE";

export const WS_ORDER_CONNECTION_START = "WS_ORDER_CONNECTION_START";
export const WS_ORDER_SEND_MESSAGE = "WS_ORDER_SEND_MESSAGE";
export const WS_ORDER_CLOSE = "WS_ORDER_CLOSE";
